- hosts: localhost

  roles:
  - role: openmicroscopy.omero-web

  tasks:

  - name: django whitenoise | install
    become: yes
    pip:
      name: whitenoise
      state: present
      virtualenv: "{{ omero_web_basedir }}/venv"
      virtualenv_site_packages: yes

  - name: django whitenoise | enable
    become: yes
    copy:
      content: |
        config append -- omero.web.middleware '{"index": 0, "class": "whitenoise.middleware.WhiteNoiseMiddleware"}'
      dest: "{{ omero_web_basedir }}/config/whitenoise.omero"
      force: yes

  vars:
    ice_version: "3.6"
    ice_install_devel: False
    omero_web_systemd_setup: False
    omero_web_setup_nginx: False
    ice_python_wheel: https://github.com/openmicroscopy/zeroc-ice-py-centos7/releases/download/0.0.2/zeroc_ice-3.6.3-cp27-cp27mu-linux_x86_64.whl
